"use client";

import {
  BarChart3,
  TrendingUp,
  AlertTriangle,
  Users,
  FileText,
  MessageCircle,
  Sparkles,
} from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { KpiCard } from "@/components/kpi-card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  REPORT_SUMMARY,
  MOST_ASKED_QUESTIONS,
  KNOWLEDGE_GAPS,
  DEPARTMENT_ACTIVITY,
  ANALYTICS_KPIS,
  KNOWLEDGE_COVERAGE,
  TRAINING_PROGRESS,
} from "@/lib/mock-data";

const KPI_ICONS = { Users, FileText, MessageCircle, Sparkles } as const;

export default function ReportsPage() {
  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-page-title">Reports</h1>
        <p className="text-caption text-muted-foreground">
          Daily and weekly summaries, usage analytics, knowledge gap detection.
        </p>
      </div>

      <Tabs defaultValue="overview">
        <TabsList>
          <TabsTrigger value="overview" className="gap-1.5">
            <BarChart3 className="size-4" />
            Overview
          </TabsTrigger>
          <TabsTrigger value="analytics" className="gap-1.5">
            <TrendingUp className="size-4" />
            Analytics
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="flex flex-col gap-4">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <Card className="shadow-soft-sm">
              <CardHeader>
                <CardTitle>Daily Summary</CardTitle>
                <CardDescription>Generated by Reporter AI</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-caption">{REPORT_SUMMARY.daily}</p>
              </CardContent>
            </Card>
            <Card className="shadow-soft-sm">
              <CardHeader>
                <CardTitle>Weekly Summary</CardTitle>
                <CardDescription>Generated by Reporter AI</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-caption">{REPORT_SUMMARY.weekly}</p>
              </CardContent>
            </Card>
          </div>

          <Card className="shadow-soft-sm">
            <CardHeader>
              <CardTitle>Most Asked Questions</CardTitle>
              <CardDescription>Across all departments this week</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              {MOST_ASKED_QUESTIONS.map((q) => (
                <div
                  key={q.id}
                  className="flex flex-col gap-2 rounded-[var(--radius-lg)] border border-border px-3 py-2.5 sm:flex-row sm:items-center sm:justify-between"
                >
                  <div className="flex flex-col">
                    <span className="font-medium">{q.question}</span>
                    <span className="text-caption text-muted-foreground">{q.department}</span>
                  </div>
                  <Badge variant="secondary" className="self-start sm:self-auto">{q.count} asked</Badge>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="shadow-soft-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="size-4 text-warning" />
                Knowledge Gap Detection
              </CardTitle>
              <CardDescription>
                Topics where Buddy AI couldn&apos;t find a confident answer
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              {KNOWLEDGE_GAPS.map((gap) => (
                <div
                  key={gap.id}
                  className="flex flex-col gap-2 rounded-[var(--radius-lg)] border border-warning/30 bg-warning/5 px-3 py-2.5 sm:flex-row sm:items-center sm:justify-between"
                >
                  <div className="flex flex-col">
                    <span className="font-medium">{gap.topic}</span>
                    <span className="text-caption text-muted-foreground">{gap.department}</span>
                  </div>
                  <Badge variant="secondary" className="self-start text-warning sm:self-auto">
                    {gap.occurrences} occurrences
                  </Badge>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="analytics" className="flex flex-col gap-4">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {ANALYTICS_KPIS.map((kpi) => (
              <KpiCard
                key={kpi.label}
                label={kpi.label}
                value={kpi.value}
                change={kpi.change}
                icon={KPI_ICONS[kpi.icon as keyof typeof KPI_ICONS]}
              />
            ))}
          </div>

          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <Card className="shadow-soft-sm">
              <CardHeader>
                <CardTitle>Knowledge Coverage</CardTitle>
                <CardDescription>How well each category is covered by documents</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                {KNOWLEDGE_COVERAGE.map((item) => (
                  <div key={item.category} className="flex flex-col gap-1.5">
                    <div className="flex items-center justify-between text-caption">
                      <span>{item.category}</span>
                      <span className="text-muted-foreground">{item.coverage}%</span>
                    </div>
                    <Progress value={item.coverage} />
                  </div>
                ))}
              </CardContent>
            </Card>

            <Card className="shadow-soft-sm">
              <CardHeader>
                <CardTitle>Training Progress</CardTitle>
                <CardDescription>Organization-wide learning</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                {TRAINING_PROGRESS.map((item) => (
                  <div key={item.id} className="flex flex-col gap-1.5">
                    <div className="flex items-center justify-between text-caption">
                      <span>{item.title}</span>
                      <span className="text-muted-foreground">{item.progress}%</span>
                    </div>
                    <Progress value={item.progress} />
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          <Card className="shadow-soft-sm">
            <CardHeader>
              <CardTitle>Department Activity</CardTitle>
              <CardDescription>AI usage broken down by department</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Department</TableHead>
                    <TableHead>Questions Asked</TableHead>
                    <TableHead>Active Users</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {DEPARTMENT_ACTIVITY.map((row) => (
                    <TableRow key={row.department}>
                      <TableCell className="font-medium">{row.department}</TableCell>
                      <TableCell>{row.questions}</TableCell>
                      <TableCell>{row.activeUsers}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
